# Author: Maximilian Vogeltanz, University of Graz, 2025

# Script to post-process the raw RDF-XML Output generated by LLM.
# Step 1: Every string that is invalid xml i.e. outside of transaction logic gets commented out, because it resembles additional comments from the LLM.
# Step 2: Inserts RDF header around the entire data, also adds 2 generic elements (<gams:isMemberofCollection> and <gams:isPartOf>)
# Step 3: Fixes invalid strings that are common bugs in the LLM output. Can be extended/adapted as needed.
# Step 4: Remove empty lines from the output.
# Step 5: Validates/sanitizes the RDF by splitting multinode properties into valid RDF (f.e. 1 bk:transfers with 2 children bk:Money gets converted to 2 bk:transfers with 1 child bk:Money for each)
# Step 6: Resolves date phrases deterministically. The LLM is asked to COPY the date phrase
#         out of the entry into bk:when/@resolve-from rather than to compute a date; this step
#         turns the phrase into an ISO date with latin_dates.py (next to this file). Where a
#         block carries no @resolve-from (older output, or an entry with no date phrase), the
#         step falls back to VERIFYING the existing bk:when and only reports what it would
#         have computed.
# Step 7: Validates the RDF against the JSON that was fed to the LLM: every id present (no missing/extra/duplicate), each <bk:entry> equals the JSON entry, each arec:hasRubric matches the JSON rubric (compared by #anchor). The pointer/arec:recordedBy check is kept but stays silent for the ground-truth data in this repository, which carries no "pointer" field. Reports only — does not abort.
# Step 8: Final well-formedness check. Re-reads the file FROM DISK after the interactive
#         corrections of step 7 have been written, so it judges the file as it now stands —
#         not the in-memory tree. Verifies that it still parses, that the RDF skeleton is
#         intact and that no postprocessing leftovers remain.

# PIPELINE ORDER — IMPORTANT:
#   LLM_Processor.py  ->  postprocess_RDF_output.py (this script)  ->  compare_RDF.py
#   Run this on the raw output of LLM_Processor.py (output/JSONtoRDF/raw/), then evaluate
#   the postprocessed result against the ground truth with compare_RDF.py.

from lxml import etree as ET
import os
import re
import sys
import json
import difflib

sys.stdout.reconfigure(encoding='utf-8')

# The deterministic date resolver (see Step 6 below). Lives in this folder.
import latin_dates

# The deterministic amount reader (see Step 7b below). Same division of labour as the date
# resolver: the model selects, this computes.
import latin_amounts

# ──────────────── Paths ─────────────────
# All paths stay inside this repository. base_dir is output/JSONtoRDF/.
base_dir = os.path.dirname(os.path.abspath(__file__))
repo_dir = os.path.dirname(os.path.dirname(base_dir))
rdf_input_path = os.path.join(base_dir, "raw", "L343GT_qwen3.5-397b.xml") # adapt as needed
rdf_output_path = os.path.join(base_dir, "postprocessed", "L343GT_qwen3.5-397b.xml") # adapt as needed

# JSON that was fed to the JSONtoRDF LLM step. Used at the end to validate that the LLM did
# not alter texts/ids/rubrics. Set to None to skip the check.
json_reference_path = os.path.join(
    repo_dir, "data", "standalone_entries_L343GT.json"
)  # adapt as needed

os.makedirs(os.path.dirname(rdf_output_path), exist_ok=True)

# ──────────────── Step 1: Comment invalid lines ─────────────────
def comment_invalid_text(input_path, output_path):
    with open(input_path, "r", encoding="utf-8") as f:
        content = f.read()

    commented_lines = []
    in_comment = False
    
    for line in content.splitlines():
        stripped = line.strip()
        
        # Track if we're inside a comment block
        if '<!--' in line:
            in_comment = True
        if '-->' in line:
            in_comment = True  # This line is part of comment
            commented_lines.append(line)
            in_comment = False
            continue
            
        # If inside comment, keep as is
        if in_comment:
            commented_lines.append(line)
        # Strip embedded XML declarations and RDF wrapper tags (LLM wraps each block in its own document)
        elif stripped.startswith("<?xml") or stripped.startswith("<rdf:RDF") or stripped.startswith("</rdf:RDF>"):
            commented_lines.append(f"<!-- {stripped} -->")
        # If line is invalid (not XML and not empty), comment it
        # LIMITATION: This check is line-by-line. If an XML element's text content spans
        # multiple lines, continuation lines (which don't start with "<") will be wrongly
        # commented out. In practice this is not an issue because LLM output for structured
        # data keeps element content on a single line, but be aware if output format changes.
        elif stripped and not stripped.startswith("<"):
            commented_lines.append(f"<!-- {stripped} -->")
        else:
            commented_lines.append(line)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(commented_lines))

comment_invalid_text(rdf_input_path, rdf_output_path)

# ──────────────── Step 2: Insert RDF header and footer, add "<gams:isMemberofCollection> and <gams:isPartOf>" ─────────────────
rdf_header = """<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:bk="https://gams.uni-graz.at/o:depcha.bookkeeping#" xmlns:arec="https://gams.uni-graz.at/o:arec.ontology#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:depcha="https://gams.uni-graz.at/o:depcha.ontology#"
    xmlns:functx="http://www.functx.com"
    xmlns:gams="https://gams.uni-graz.at/o:gams-ontology#"
    xmlns:gn="http://www.geonames.org/ontology#"
    xmlns:huc="https://gams.uni-graz.at/o:depcha.huc-ontology#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:schema="https://schema.org/"
    xmlns:skos="http://www.w3.org/2004/02/skos/core#"
    xmlns:t="http://www.tei-c.org/ns/1.0"
    xmlns:time="http://www.w3.org/2006/time#"
    xmlns:void="http://rdfs.org/ns/void#">
"""

def insert_rdf_header_footer(path):
    with open(path, "r", encoding="utf-8") as f:
        body = f.read().strip()
    # Only insert if not already present — check the START of the body, not anywhere inside
    body_check = body
    if body_check.startswith("<?xml"):
        body_check = body_check[body_check.find("?>") + 2:].strip()
    if not body_check.startswith("<rdf:RDF"):
        wrapped = rdf_header + "\n" + body + "\n</rdf:RDF>\n"
        with open(path, "w", encoding="utf-8") as f:
            f.write(wrapped)
        print("✅ RDF header and footer inserted.")
    else:
        print("ℹ️ RDF header/footer already present — skipping.")

insert_rdf_header_footer(rdf_output_path)

# add "<gams:isMemberOfCollection rdf:resource="https://gams.uni-graz.at/context:arec"/>" below bk:Transaction
def add_collection_membership(input_path, output_path):
    parser = ET.XMLParser(remove_blank_text=False)
    tree = ET.parse(input_path, parser)
    root = tree.getroot()

    BK_NS = "https://gams.uni-graz.at/o:depcha.bookkeeping#"
    GAMS_NS = "https://gams.uni-graz.at/o:gams-ontology#"
    RDF_NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    AREC_NS = "https://gams.uni-graz.at/o:arec.ontology#"

    nsmap = {
        "bk": BK_NS,
        "gams": GAMS_NS,
        "rdf": RDF_NS,
        "arec": AREC_NS,
    }

    # Collect all relevant RDF entities
    transactions = root.xpath("//bk:Transaction", namespaces=nsmap)
    totaltransactions = root.xpath("//bk:TotalTransaction", namespaces=nsmap)
    notas = root.xpath("//arec:Note", namespaces=nsmap)

    targets = transactions + totaltransactions + notas

    added = 0

    for tx in targets:

        # Get base URI from rdf:about
        about = tx.get(f"{{{RDF_NS}}}about")
        if about and "#" in about:
            base_uri = about.split("#")[0]
        else:
            # Skip entities without rdf:about (should not happen, but safe)
            continue

        # 1. Insert gams:isMemberOfCollection (if missing)
        existing_member = tx.xpath("./gams:isMemberOfCollection", namespaces=nsmap)
        if not existing_member:
            member_el = ET.Element(f"{{{GAMS_NS}}}isMemberOfCollection")
            member_el.set(f"{{{RDF_NS}}}resource",
                          "https://gams.uni-graz.at/context:arec")
            tx.insert(0, member_el)

        # 2. Insert gams:isPartOf (if missing)
        existing_part = tx.xpath("./gams:isPartOf", namespaces=nsmap)
        if not existing_part:
            part_el = ET.Element(f"{{{GAMS_NS}}}isPartOf")
            part_el.set(f"{{{RDF_NS}}}resource", base_uri)
            # Insert AFTER isMemberOfCollection = index 1
            tx.insert(1, part_el)

        added += 1

    tree.write(output_path, encoding="utf-8", xml_declaration=True, pretty_print=True)
    print(
        f"✅ Added gams:isMemberOfCollection + gams:isPartOf to {added} elements (in: Transaction/TotalTransaction/Nota). Uri = {base_uri}"
    )

add_collection_membership(rdf_output_path, rdf_output_path)


# ──────────────── Step 3: Fix invalid strings ─────────────────
with open(rdf_output_path, "r", encoding="utf-8") as f:
    content = f.read()

content = content.replace('<!-- --- -->', '')
#content = re.sub(r'<bk:status>.*?</bk:status>', '', content) # Removing bk:status
content = content.replace('``````xml', '').replace('```xml', '') # remove typical invalid output
content = content.replace('```', '')
content = content.replace('```rdf', '') # remove typical invalid output
content = content.replace(' xmlns:bk="https://gams.uni-graz.at/context:arec#"', '') # remove typical invalid output
content = content.replace('bk:Transaction xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"', 'bk:Transaction') # remove typical invalid output
content = content.replace('<!--  -->', '') # remove empty comments


# optional deletion of rdf:about attributes
#content = re.sub(r'(<bk:Transaction )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<arec:Note )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<bk:TotalTransaction )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<bk:SubTotalTransaction )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<bk:Transfer )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<bk:Money )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<bk:Commodity )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<bk:Service )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<bk:Right )rdf:about=".*?"(>)', r'\1\2', content)
#content = re.sub(r'(<arec:Debt )rdf:about=".*?"(>)', r'\1\2', content)

content = re.sub(r'\n\s*\n', '\n', content) # Remove empty lines (including lines with only spaces or tabs)
# Normalize the unit URI "…#stück"/"…#stuck" -> "…#piece". IMPORTANT: only touch the
# URI anchor (preceded by "#"), NOT the free word "stück" that may legitimately occur
# inside <bk:entry> transcription text (e.g. "geverbt stuck ...").
content = re.sub(r'(?<=#)st[üu]ck\b', 'piece', content, flags=re.IGNORECASE) # #stück / #stuck -> #piece

with open(rdf_output_path, "w", encoding="utf-8") as f:
    f.write(content)

# remove all code comments
def remove_all_comments(input_path):
    parser = ET.XMLParser(remove_blank_text=False, remove_comments=True)
    tree = ET.parse(input_path, parser)
    tree.write(input_path, encoding="utf-8", xml_declaration=True, pretty_print=True)
    print("✅ All comments removed.")
remove_all_comments(rdf_output_path)


print("✅ Commenting and cleanup complete.")


# ──────────────── Step 5: RDF Cleaner / Validation ─────────────────
BK_NS = "https://gams.uni-graz.at/o:depcha.bookkeeping#"

def split_multinode_properties_generic(tree: ET._ElementTree):
    changed = False
    fixed_count = 0
    root = tree.getroot()

    # List of parent tags to process
    parent_tags = ["transfers", "ows", "consistsOf"]  # Add more if needed
    # List of child element types to check for multinode properties
    child_types = ["Money", "Commodity", "Service", "Right", "Debt"]  # Add more if needed

    for tag_name in parent_tags:
        xpath_expr = f"//bk:{tag_name}"
        for prop in root.xpath(xpath_expr, namespaces={"bk": BK_NS}):
            # Keep only element children and skip comments/PIs/etc.
            element_children = [c for c in prop if isinstance(getattr(c, "tag", None), str)]
            # Check for any child type in the list
            for child_type in child_types:
                children = [c for c in element_children if ET.QName(c).localname == child_type]
                if len(children) <= 1:
                    continue
                parent = prop.getparent()
                if parent is None:
                    continue
                attrib_copy = dict(prop.attrib)
                idx = parent.index(prop)
                # Remove original property and reinsert split ones
                parent.remove(prop)
                for offset, child in enumerate(children):
                    new_prop = ET.Element(prop.tag, attrib=attrib_copy, nsmap=prop.nsmap)
                    new_prop.append(child)
                    parent.insert(idx + offset, new_prop)
                changed = True
                fixed_count += 1
                break  # Only split once per parent tag

    return changed, fixed_count


# Back-reference words the LLM sometimes writes as if they were a person id, e.g.
# "dedimus eidem ..." -> <bk:to rdf:resource=".../context:arec#eidem"/>. Such a URI names
# nobody — it is the Latin word for "the same one", not an identity. The ground truth never
# uses these, so they are reset to #anonymous, which is also what the coreference pass
# (step 4) needs: it may only resolve a slot that is marked as unknown.
#
# This is a safety net, not the primary fix — the JSONtoRDF prompt should not produce these
# in the first place. It stays because a prompt is a tendency, not a guarantee.
#
# Deliberately EXCLUDED are all one- and two-letter forms and anything that could be read as
# a Roman numeral or a coin abbreviation ("ii" = 2, "is", "id", "ea", "ei", "eo", "se", "hi").
# The demonstratives (hic/ille) are left out too: they are not used as agent ids in practice
# and their short forms carry the same collision risk. Verified against 759 distinct agent
# URIs across all books — the list below matches only genuine back-references.
_BACKREF_AGENTS = {
    # idem, eadem, idem — "the same"
    "idem", "eidem", "eadem", "eodem", "eundem", "eandem", "earundem", "eorundem",
    "eiusdem", "iidem", "isdem", "iisdem", "eisdem", "eaedem", "eosdem", "easdem",
    # ipse — "himself/herself/themselves"
    "ipse", "ipsa", "ipsum", "ipsius", "ipsi", "ipsam", "ipso", "ipsorum", "ipsarum",
    "ipsis", "ipsos", "ipsas",
    # is, ea, id (longer forms only) and the reflexive
    "eius", "eum", "eam", "eorum", "earum", "eis", "eos", "eas", "sibi", "sese", "secum",
    # "the aforementioned"
    "predictus", "predicto", "predicti", "prefatus", "prefato",
    "dictus", "dicto", "dicti", "supradictus", "supradicto",
    # German equivalents, for the vernacular account books
    "derselbe", "demselben", "denselben", "dieselbe", "demselbigen", "denselbigen",
}
_AGENT_TAGS = ("from", "to", "by", "credit", "debit")


def normalize_backreference_agents(tree):
    """Reset agent references that are merely a back-reference word to #anonymous.
    Only the fragment after '#' changes, so each URI keeps its own base."""
    res_attr = "{http://www.w3.org/1999/02/22-rdf-syntax-ns#}resource"
    hits = {}
    xp = " | ".join(f"//*[local-name()='{t}']" for t in _AGENT_TAGS)
    for el in tree.xpath(xp):
        uri = el.get(res_attr)
        if not uri or "#" not in uri:
            continue
        base, frag = uri.rsplit("#", 1)
        if frag.lower() in _BACKREF_AGENTS:
            el.set(res_attr, f"{base}#anonymous")
            key = f"{ET.QName(el).localname}:{frag}"
            hits[key] = hits.get(key, 0) + 1
    if hits:
        total = sum(hits.values())
        detail = ", ".join(f"{k}={v}" for k, v in sorted(hits.items()))
        print(f"✅ {total} back-reference agent(s) reset to #anonymous ({detail})")
    else:
        print("✅ No back-reference words used as agent ids.")
    return hits


def sanitize_rdfxml(input_path, output_path):
    parser = ET.XMLParser(remove_blank_text=False, resolve_entities=False)
    tree = ET.parse(input_path, parser)
    changed, fixed_count = split_multinode_properties_generic(tree)
    normalize_backreference_agents(tree)
    tree.write(output_path, encoding="utf-8", xml_declaration=True, pretty_print=True)
    if changed:
        print(f"✅ Sanitized RDF/XML written: {output_path} ({fixed_count} fixes applied)")
    else:
        print(f"✅ RDF/XML sanitized (no fixes needed): {output_path}")

# ──────────────── Step 4: Remove empty lines ─────────────────
with open(rdf_output_path, "r", encoding="utf-8") as f:
    content = f.read()
content = re.sub(r'\n\s*\n', '\n', content)
with open(rdf_output_path, "w", encoding="utf-8") as f:
    f.write(content)
print("✅ Empty lines removed.")

sanitize_rdfxml(rdf_output_path, rdf_output_path)


# ──────────────── Step 6: Resolve date phrases to ISO dates ─────────────────
# WHY THE LLM DOES NOT COMPUTE DATES
# ----------------------------------
# Measured on L343: of 1077 entries carrying a date marker, the model's bk:when agreed
# with the arithmetic in 331. It is not bad at recognising a date — it is bad at
# converting one. "dominica post festum Ascensionis domini" 1455 is 18 May (Ascension
# falls on Thursday 15 May); the model wrote 21 May, a systematic one-week drift on
# post/ante that recurs 68 times for Ascension alone.
#
# So the work is split. The model COPIES the date phrase out of bk:entry into
# bk:when/@resolve-from — a selection task, where it is good and where its answer can be
# checked against the entry text. This step computes the date from that phrase, which is
# pure Julian-calendar arithmetic and belongs in code.
#
# WHAT HAPPENS WHEN A PHRASE CANNOT BE RESOLVED
# ---------------------------------------------
# bk:when falls back to the bare year from the JSON. That is not a defeat: the ground
# truth encodes a plain YYYY on undated entries as a matter of course (154 of its 312
# bk:when values). Losing precision costs little; guessing a day costs correctness, and
# a wrong date is indistinguishable from a right one downstream. Every fallback is
# reported with its reason, so a gap in the lexicon shows up as a pattern to close
# rather than disappearing into the output.
_WHEN_ATTR = "resolve-from"


def _entry_year(entity, json_by_id, ns):
    """The fallback year for one booking: the JSON's, else the year already standing in
    a bk:when. An `Anno <roman>` inside the entry overrides this, but that is decided in
    latin_dates.parse_anno, which refuses anything implausible rather than guessing."""
    obj = json_by_id.get(entity.get(f"{{{_RDF_NS}}}about"))
    if obj and str(obj.get("year") or "").strip().isdigit():
        return int(str(obj["year"]).strip())
    for w in entity.xpath(".//bk:when", namespaces=ns):
        if w.text and re.match(r"\d{4}", w.text.strip()):
            return int(w.text.strip()[:4])
    return None


def resolve_date_phrases(rdf_path, json_path):
    ns = {"bk": _BK_NS, "arec": _AREC_NS, "rdf": _RDF_NS}
    tree = ET.parse(rdf_path)
    root = tree.getroot()

    json_by_id = {}
    if json_path and os.path.exists(json_path):
        json_by_id = {o["id"]: o for o in json.loads(open(json_path, encoding="utf-8").read())
                      if isinstance(o, dict) and o.get("id")}

    entities = root.xpath("//bk:Transaction|//arec:Note|//bk:TotalTransaction", namespaces=ns)
    resolved = fell_back = 0
    # Keyed by (booking, phrase, iso), not by booking alone. A booking with three
    # transfers usually carries the SAME date three times and should be reported once —
    # but a booking may legitimately carry several DIFFERENT dates, one per transfer, and
    # those must stay separate rows.
    reasons, flagged, verify_differs, multi_when = {}, {}, [], []
    # Whether each copied phrase really stands in its bk:entry. The prompt requires it
    # "character for character" and nothing used to check it — see _phrase_in_entry.
    when_provenance = []

    for entity in entities:
        year = _entry_year(entity, json_by_id, ns)
        entry_el = entity.find("bk:entry", ns)
        entry_text = entry_el.text if entry_el is not None else ""
        about = _anchor(entity.get(f"{{{_RDF_NS}}}about") or "?")

        # A booking may name several dates — but a single transfer or debt happens on ONE
        # day, so more than one bk:when under the same host is always an encoding error.
        for host in entity.xpath(".//bk:Transfer|.//arec:Debt", namespaces=ns):
            whens = host.xpath("./bk:when", namespaces=ns)
            if len(whens) > 1:
                multi_when.append((about, _anchor(host.get(f"{{{_RDF_NS}}}about") or "?"),
                                   [w.get(_WHEN_ATTR) or (w.text or "") for w in whens]))

        phrased = [w for w in entity.xpath(".//bk:when", namespaces=ns)
                   if w.get(_WHEN_ATTR)]

        if not phrased:
            # No phrase to resolve. Do not touch the value — only say what the
            # arithmetic would have produced, so that running this on older output is a
            # measurement and never a silent rewrite.
            expr, _why = latin_dates.resolve(entry_text or "", year)
            for w in entity.xpath(".//bk:when", namespaces=ns):
                if expr and w.text and len(w.text.strip()) > 4 and w.text.strip() != expr.iso:
                    verify_differs.append((about, w.text.strip(), expr.iso, expr.span))
                    break
            continue

        for w in phrased:
            phrase = w.get(_WHEN_ATTR)
            when_provenance.append((_phrase_in_entry(phrase, entry_text), about, phrase))
            expr, why = latin_dates.resolve_phrase(phrase, year)
            del w.attrib[_WHEN_ATTR]

            if expr is None:
                fell_back += 1
                reasons.setdefault(why or "?", set()).add((about, phrase))
                w.text = str(year) if year else None
                continue

            resolved += 1
            w.text = expr.iso

            # The model chose this phrase; the resolver cannot second-guess that choice,
            # only surface the cases where it is most likely to have gone wrong.
            marks = []
            if expr.ambiguous:
                marks.append("feast name is also a personal name")
            if latin_dates.DEADLINE_MARKERS.search(entry_text or ""):
                marks.append("entry contains a payment-deadline marker")
            if expr.year_source == "entry":
                marks.append(f"year {expr.year} read from the entry, not the JSON")
            if marks:
                flagged[(about, phrase, expr.iso)] = "; ".join(marks)

    # Structural, independent of whether anything was resolved.
    if multi_when:
        print(f"\n⚠️ {len(multi_when)} transfer(s)/debt(s) carry more than one bk:when. "
              f"A booking may name several dates — one per transfer — but a single "
              f"transfer or debt happens on one day:")
        for about, host, vals in multi_when[:20]:
            print(f"    {about} / {host}: {', '.join(str(v) for v in vals)}")
        if len(multi_when) > 20:
            print(f"    … and {len(multi_when) - 20} more")

    if resolved or fell_back:
        tree.write(rdf_path, encoding="utf-8", xml_declaration=True, pretty_print=True)
        print(f"✅ Dates resolved: {resolved} phrase(s) -> ISO, "
              f"{fell_back} fell back to the bare year.")
        if reasons:
            print(f"\n⚠️ {fell_back} phrase(s) fell back to the bare year — close these "
                  f"as patterns in latin_dates.py, not case by case:")
            for why, items in sorted(reasons.items(), key=lambda kv: -len(kv[1])):
                print(f"    {len(items):4}  {why}")
                for about, phrase in sorted(items)[:3]:
                    print(f"          {about}: {phrase!r}")
        if flagged:
            print(f"\nℹ️ {len(flagged)} resolved date(s) worth a look — the arithmetic is "
                  f"sound, the CHOICE of phrase is the model's and may not be:")
            for (about, phrase, iso), mark in sorted(flagged.items())[:25]:
                print(f"    {about}: {phrase!r} -> {iso}  ({mark})")
            if len(flagged) > 25:
                print(f"    … and {len(flagged) - 25} more")
    else:
        print("ℹ️ No bk:when/@resolve-from found — nothing resolved. "
              "(The model is still writing dates itself; see the note above.)")
        if verify_differs:
            print(f"\n⚠️ {len(verify_differs)} bk:when differ(s) from what the resolver "
                  f"computes for the entry. Report only, nothing was changed:")
            for about, had, should, span in verify_differs[:20]:
                print(f"    {about}: has {had}, phrase {span!r} gives {should}")
            if len(verify_differs) > 20:
                print(f"    … and {len(verify_differs) - 20} more")
            print("    (the resolver's own reading of the phrase is in latin_dates.py)")

    _report_phrase_provenance("bk:when", when_provenance)


# ──────────────── Provenance of a copied phrase ─────────────────
# Shared by the date resolution above. Amount resolution once lived here too and was
# removed again; latin_amounts.py and its tests are kept for a future attempt.
def _phrase_in_entry(phrase, entry_text):
    """Does the copied phrase really stand in the entry? -> "exact" | "case" | "absent".

    The prompt requires the phrase to occur "character for character", but until now
    nothing checked it. That check is what makes the split safe: the resolver's arithmetic
    is sound by construction, so the only remaining way to get a wrong value is a phrase
    that was never in the source. Whitespace is normalised on both sides because the JSON
    wraps long entries.
    """
    hay, needle = _nw(entry_text), _nw(phrase)
    if not needle:
        return "absent"
    if needle in hay:
        return "exact"
    return "case" if needle.lower() in hay.lower() else "absent"


def _report_phrase_provenance(label, provenance):
    """Print what the containment check found, for one kind of resolve-from."""
    off_case = [p for p in provenance if p[0] == "case"]
    absent = [p for p in provenance if p[0] == "absent"]
    if not off_case and not absent:
        if provenance:
            print(f"✅ all {len(provenance)} {label}/@resolve-from phrase(s) occur in "
                  f"their bk:entry character for character.")
        return
    if off_case:
        print(f"\nℹ️ {len(off_case)} {label}/@resolve-from phrase(s) differ from the entry "
              f"only in capitalisation:")
        for _k, about, phrase in off_case[:10]:
            print(f"    {about}: {phrase!r}")
    if absent:
        print(f"\n⚠️ {len(absent)} {label}/@resolve-from phrase(s) do NOT occur in their "
              f"bk:entry. The value was still computed, but from a phrase the source does "
              f"not contain — check these before trusting them:")
        for _k, about, phrase in absent[:20]:
            print(f"    {about}: {phrase!r}")
        if len(absent) > 20:
            print(f"    … and {len(absent) - 20} more")


# ──────────────── Step 7: Validate RDF against the JSON input ─────────────────
# The JSONtoRDF LLM step is the one that reworks the text the most, so it can silently
# alter the very things the earlier postprocessing steps guard: the entry text, the id
# (rdf:about) and the pointer (arec:recordedBy). This stage compares the final RDF against
# the JSON that was fed to the step and reports (does NOT abort — this is the last step):
#   A) completeness  — every JSON id present as rdf:about, no extra/hallucinated ids;
#   B) bk:entry      — each entity's <bk:entry> equals the JSON 'entry' (whitespace-normalised);
#   C) pointer       — arec:recordedBy matches the JSON 'pointer', comparing only the '#anchor'
#                      (so the short form "o:arec…#x" and the full URL "https://…#x" are equal).
_BK_NS = "https://gams.uni-graz.at/o:depcha.bookkeeping#"
_AREC_NS = "https://gams.uni-graz.at/o:arec.ontology#"
_RDF_NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"

def _nw(t):
    return re.sub(r"\s+", " ", str(t or "")).strip()

def _anchor(uri):
    # Compare pointers by their fragment only; short form and full URL share the '#x' tail.
    s = _nw(uri)
    return s.split("#", 1)[1] if "#" in s else s

def validate_rdf_against_json(rdf_path, json_path):
    if not json_path or not os.path.exists(json_path):
        print("ℹ️ No JSON reference set/found — skipping RDF-vs-JSON validation.")
        return

    data = json.loads(open(json_path, "r", encoding="utf-8").read())
    json_by_id = {o["id"]: o for o in data if isinstance(o, dict) and o.get("id")}

    # The final output is a valid single RDF document, so parse it directly.
    ns = {"bk": _BK_NS, "arec": _AREC_NS, "rdf": _RDF_NS}
    root = ET.parse(rdf_path).getroot()
    entities = root.xpath("//bk:Transaction|//arec:Note|//bk:TotalTransaction", namespaces=ns)

    rdf_ids = []
    no_about = 0             # entities lacking an rdf:about attribute
    entry_mismatch = []      # (id, json_entry, rdf_entry, bk_entry_element)
    pointer_mismatch = []    # (id, json_pointer, rdf_pointer, pointsTo_element_or_None)
    rubric_mismatch = []     # (id, json_rubric, rdf_rubric, hasRubric_el_or_None, entity)
    year_mismatch = []       # (id, json_year, [differing bk:when values])
    same_party = []          # (id, transfer/debt id, "from/to", the duplicated party)
    missing_entry_tag = []   # id

    for e in entities:
        about = e.get(f"{{{_RDF_NS}}}about")
        if about is None:
            no_about += 1
            continue
        rdf_ids.append(about)
        jo = json_by_id.get(about)
        if jo is None:
            continue  # completeness handled below

        et = e.xpath("./bk:entry", namespaces=ns)
        if not et:
            missing_entry_tag.append(about)
        else:
            expected = _nw(jo.get("entry"))
            actual = _nw(et[0].text)
            if expected != actual:
                entry_mismatch.append((about, expected, actual, et[0]))

        jptr = jo.get("pointer")
        if jptr:
            pts = e.xpath("./arec:recordedBy", namespaces=ns)
            pt_el = pts[0] if pts else None
            pt_val = pt_el.get(f"{{{_RDF_NS}}}resource") if pt_el is not None else None
            if pt_val is None or _anchor(pt_val) != _anchor(jptr):
                pointer_mismatch.append((about, jptr, pt_val, pt_el))

        # Steps 1 and 2 both verify that rubric/year/pointer are inherited unchanged
        # (their META_FIELDS / FIELDS lists). This step used to check only entry and
        # pointer — which is where the fields change shape from JSON keys to RDF
        # elements, so it is the LEAST safe place to leave a gap, not the safest.
        jrub = jo.get("rubric")
        if jrub:
            rbs = e.xpath("./arec:hasRubric", namespaces=ns)
            rb_el = rbs[0] if rbs else None
            rb_val = rb_el.get(f"{{{_RDF_NS}}}resource") if rb_el is not None else None
            if rb_val is None or _anchor(rb_val) != _anchor(jrub):
                rubric_mismatch.append((about, jrub, rb_val, rb_el, e))

        # The year is compared against the leading YYYY of every bk:when. Reported only:
        # at a year boundary the ledgers' Christmas-style reckoning (the year begins on
        # 25 December) makes the correct value a judgement call, not a lookup.
        jyear = _nw(jo.get("year"))
        if jyear:
            bad = [w for w in (_nw(x.text) for x in e.xpath(".//bk:when", namespaces=ns))
                   if w and w[:4].isdigit() and w[:4] != jyear]
            if bad:
                # The entry text comes along: most of these are decidable by eye, because
                # the entry names its own year ("de anno lvio") or its own feast day.
                year_mismatch.append((about, jyear, bad, _nw(jo.get("entry"))))

        # A transfer runs BETWEEN two parties, so the same named party must not stand on
        # both sides. Placeholders are exempt — two #anonymous slots are two unknown
        # parties, not one party twice — and so is the rubric term, for the same reason.
        rt = _anchor(jo.get("rubric") or "")
        rt = rt.split("_", 1)[1] if "_" in rt else rt
        for host_xpath, (left, right) in ((".//bk:Transfer", ("from", "to")),
                                          (".//arec:Debt", ("credit", "debit"))):
            for node in e.xpath(host_xpath, namespaces=ns):
                ls = node.xpath(f"./bk:{left}", namespaces=ns)
                rs = node.xpath(f"./bk:{right}", namespaces=ns)
                if not ls or not rs:
                    continue
                lv = _anchor(ls[0].get(f"{{{_RDF_NS}}}resource") or "")
                rv = _anchor(rs[0].get(f"{{{_RDF_NS}}}resource") or "")
                if lv and lv == rv and lv != "anonymous" and lv != rt:
                    same_party.append((about, node.get(f"{{{_RDF_NS}}}about"),
                                       f"{left}/{right}", lv))

    json_ids = set(json_by_id)
    rdf_id_set = set(rdf_ids)
    missing_in_rdf = sorted(json_ids - rdf_id_set)
    extra_in_rdf = sorted(rdf_id_set - json_ids)
    duplicate_ids = sorted({i for i in rdf_ids if rdf_ids.count(i) > 1})

    print("\n──────────────── RDF vs JSON validation ────────────────")
    print(f"JSON objects with id: {len(json_by_id)}  |  RDF entities: {len(entities)}")

    problems = (missing_in_rdf or extra_in_rdf or duplicate_ids or no_about
                or entry_mismatch or pointer_mismatch or rubric_mismatch
                or year_mismatch or same_party or missing_entry_tag)
    if not problems:
        print("✅ Validation successful: all ids present, no extras; bk:entry, "
              "arec:recordedBy, arec:hasRubric and the bk:when year all match the JSON, "
              "and no transfer has the same party on both sides.")
        return

    if no_about:
        print(f"\n⚠️ {no_about} entit(y/ies) without an rdf:about attribute (cannot be matched to JSON).")
    if missing_in_rdf:
        print(f"\n⚠️ {len(missing_in_rdf)} id(s) in JSON but MISSING in RDF (entry dropped):")
        for i in missing_in_rdf[:20]:
            print(f"    {i}")
    if extra_in_rdf:
        print(f"\n⚠️ {len(extra_in_rdf)} id(s) in RDF but NOT in JSON (hallucinated/extra):")
        for i in extra_in_rdf[:20]:
            print(f"    {i}")
    if duplicate_ids:
        print(f"\n⚠️ {len(duplicate_ids)} id(s) appear MORE THAN ONCE in the RDF:")
        for i in duplicate_ids[:20]:
            print(f"    {i}")
    if missing_entry_tag:
        print(f"\n⚠️ {len(missing_entry_tag)} entit(y/ies) without a <bk:entry> element:")
        for i in missing_entry_tag[:20]:
            print(f"    {i}")
    def _entry_diff(j, r):
        d = difflib.SequenceMatcher(a=j.split(), b=r.split(), autojunk=False)
        marks = []
        for tag, i1, i2, k1, k2 in d.get_opcodes():
            if tag == "equal":
                continue
            if tag in ("delete", "replace"):
                marks.append("[-" + " ".join(j.split()[i1:i2]) + "-]")
            if tag in ("insert", "replace"):
                marks.append("{+" + " ".join(r.split()[k1:k2]) + "+}")
        return " ".join(marks)

    if entry_mismatch:
        print(f"\n⚠️ {len(entry_mismatch)} <bk:entry> text(s) differ from the JSON entry:")
        for about, j, r, _el in entry_mismatch[:20]:
            print(f"    {about}: {_entry_diff(j, r)}")
    if pointer_mismatch:
        print(f"\n⚠️ {len(pointer_mismatch)} arec:recordedBy differ from the JSON pointer:")
        for about, j, r, _el in pointer_mismatch[:20]:
            print(f"    {about}: expected …#{_anchor(j)}, got {r!r}")
    if rubric_mismatch:
        n_absent = sum(1 for *_x, el, _e in rubric_mismatch if el is None)
        print(f"\n⚠️ {len(rubric_mismatch)} arec:hasRubric differ from the JSON rubric "
              f"({n_absent} missing entirely):")
        for about, j, r, _el, _e in rubric_mismatch[:20]:
            print(f"    {about}: expected …#{_anchor(j)}, "
                  f"{'ELEMENT ABSENT' if r is None else f'got {r!r}'}")
    if year_mismatch:
        print(f"\n⚠️ {len(year_mismatch)} booking(s) have a bk:when whose year differs "
              f"from the JSON year (only the YYYY part is compared, so a fully dated "
              f"bk:when is not flagged for its precision):")
        for about, jy, bad, txt in year_mismatch[:40]:
            print(f"    {_anchor(about)}: JSON {jy} vs bk:when {', '.join(bad)}")
            print(f"        {txt[:150]}")
        print("    (report only — the entry usually decides it: watch for 'de anno lvio' "
              "or a named feast, and for a second date such as 'Acta sunt hec …', which is "
              "the settlement day, not the transaction day.)")
    if same_party:
        print(f"\n⚠️ {len(same_party)} transfer(s)/debt(s) with the SAME named party on "
              f"both sides (a transfer runs between two parties; placeholders are exempt):")
        for about, node_id, slots, who in same_party[:20]:
            print(f"    {_anchor(about)} / {_anchor(node_id or '?')}: {slots} both = {who}")

    # ── Interactive auto-correction to the JSON original (bk:entry text, arec:recordedBy
    #    and arec:hasRubric). The year mismatches are report-only, see above. ──
    fixable = len(entry_mismatch) + len(pointer_mismatch) + len(rubric_mismatch)
    if fixable and sys.stdin.isatty():
        print(f"\nInteractive correction: {fixable} fixable difference(s) "
              f"({len(entry_mismatch)} entry, {len(pointer_mismatch)} pointer, "
              f"{len(rubric_mismatch)} rubric).")
        print("For each, choose whether to overwrite the RDF value with the JSON original.")
        print("  [y] yes, use JSON original   [n] no, keep RDF   [q] quit correcting\n")
        applied = 0
        quit_now = False

        for about, j, r, el in entry_mismatch:
            print(f"[bk:entry] {about}")
            print(f"    {_entry_diff(j, r)}")
            ans = input("    Use JSON original? [y/n/q]: ").strip().lower()
            if ans == "q":
                quit_now = True
                break
            if ans == "y":
                el.text = j          # j is the whitespace-normalised JSON entry
                applied += 1
                print("    -> applied.\n")
            else:
                print("    -> kept RDF.\n")

        if not quit_now:
            for about, j, r, el in pointer_mismatch:
                print(f"[arec:recordedBy] {about}")
                print(f"    expected …#{_anchor(j)}, got {r!r}")
                if el is None:
                    print("    -> SKIPPED (no <arec:recordedBy> element present to edit).\n")
                    continue
                ans = input("    Use JSON original? [y/n/q]: ").strip().lower()
                if ans == "q":
                    quit_now = True
                    break
                if ans == "y":
                    el.set(f"{{{_RDF_NS}}}resource", j)
                    applied += 1
                    print("    -> applied.\n")
                else:
                    print("    -> kept RDF.\n")

        # The rubric differs from the two above: in practice it is not a wrong value but a
        # MISSING element (the model drops it on some bk:TotalTransaction blocks), so the
        # fix has to create it rather than overwrite an attribute.
        if not quit_now:
            for about, j, r, el, entity in rubric_mismatch:
                print(f"[arec:hasRubric] {about}")
                print(f"    expected …#{_anchor(j)}, "
                      f"{'ELEMENT ABSENT' if r is None else f'got {r!r}'}")
                ans = input("    Use JSON original? [y/n/q]: ").strip().lower()
                if ans == "q":
                    break
                if ans != "y":
                    print("    -> kept RDF.\n")
                    continue
                if el is not None:
                    el.set(f"{{{_RDF_NS}}}resource", j)
                    print("    -> applied.\n")
                else:
                    # Insert right after <bk:entry> so the block keeps its usual order,
                    # inheriting that element's tail for the indentation.
                    new_el = ET.Element(f"{{{_AREC_NS}}}hasRubric")
                    new_el.set(f"{{{_RDF_NS}}}resource", j)
                    ets = entity.xpath("./bk:entry", namespaces=ns)
                    if ets:
                        new_el.tail = ets[0].tail
                        ets[0].addnext(new_el)
                    else:
                        kids = list(entity)
                        new_el.tail = kids[-1].tail if kids else None
                        entity.append(new_el)
                    print("    -> created.\n")
                applied += 1

        if applied:
            root.getroottree().write(rdf_path, encoding="utf-8",
                                     xml_declaration=True, pretty_print=True)
            print(f"✅ Applied {applied} correction(s) and rewrote: {rdf_path}")
        else:
            print("No corrections applied.")
    elif fixable:
        print("\n(Non-interactive run — skipping interactive correction.)")

    print("\n(These are the LAST step's findings. Non-fixable items (missing/extra/duplicate "
          "ids, no rdf:about, missing <bk:entry>) must be fixed in the raw RDF or by re-running the LLM step.)")

# Step 6 runs before step 7 so that the JSON validation's year check sees the resolved
# dates. Both are defined further up but called here, after the shared _BK_NS/_anchor
# helpers exist.
resolve_date_phrases(rdf_output_path, json_reference_path)

validate_rdf_against_json(rdf_output_path, json_reference_path)


# ──────────────── Step 7b: Correct misread j̸ numerals ─────────────────
# The model takes the j of "j̸" for a final i (vij = 7) and adds 0.5 on top, so it lands one
# too high. The prompt does not talk it out of that, so the correction happens here.
# This step does not re-resolve amounts. It reproduces the misreading with
# latin_amounts.misread() and replaces a quantity only where it matches EXACTLY, which
# leaves selection to the model: a sum it chose differently never matches.
# Runs after step 7, on the entry text as the interactive correction left it.
def correct_stroke_quantities(rdf_path):
    ns = {"bk": _BK_NS, "arec": _AREC_NS, "rdf": _RDF_NS}
    tree = ET.parse(rdf_path)
    changed, log = 0, []

    for entity in tree.getroot().xpath(
            "//bk:Transaction|//arec:Note|//bk:TotalTransaction", namespaces=ns):
        entry_el = entity.find("bk:entry", ns)
        entry = entry_el.text if entry_el is not None else ""
        if not entry or latin_amounts._STROKE not in entry:
            continue

        # predicted misreading -> value(s) meant; `attested` = every correct reading in this
        # entry, so a number right for ANOTHER numeral is never corrected on a coincidence.
        predicted, attested = {}, set()
        for _run, right, wrong in latin_amounts.numeral_runs(entry):
            attested.add(round(right, 2))
            if wrong is not None and abs(wrong - right) > 1e-9:
                predicted.setdefault(round(wrong, 2), set()).add(round(right, 2))

        about = _anchor(entity.get(f"{{{_RDF_NS}}}about") or "?")
        for q in entity.xpath(".//bk:quantity", namespaces=ns):
            try:
                had = round(float((q.text or "").strip()), 2)
            except ValueError:
                continue
            wants = predicted.get(had)
            # Ambiguous, or already right for some term: leave it. Silence is the correct
            # failure mode.
            if not wants or len(wants) != 1 or had in attested:
                continue
            want = next(iter(wants))
            q.text = f"{want:g}"
            log.append((about, had, want))
            changed += 1

    print("\n──────────────── Stroke numerals (j̸) ────────────────")
    if not changed:
        print("✅ No quantity matched the predicted misreading — nothing changed.")
        return 0
    tree.write(rdf_path, encoding="utf-8", xml_declaration=True, pretty_print=True)
    print(f"✅ Corrected {changed} quantity/-ies that matched the model's misreading:")
    for about, had, want in log[:15]:
        print(f"    {about}: {had:g} -> {want:g}")
    if len(log) > 15:
        print(f"    … and {len(log) - 15} more")
    return changed

correct_stroke_quantities(rdf_output_path)


# ──────────────── Step 8: Final well-formedness check ─────────────────
# Re-reads the file FROM DISK, after the interactive corrections of step 7 have been
# written, and simply asks whether it is still well-formed XML.
def final_wellformedness_check(rdf_path):
    print("\n──────────────── Final well-formedness check ────────────────")
    try:
        ET.parse(rdf_path)
    except ET.XMLSyntaxError as err:
        print(f"❌ NOT well-formed: {err}")
        return False
    print(f"✅ Well-formed XML: {rdf_path}")
    return True

final_wellformedness_check(rdf_output_path)
